### PR TITLE
Add github action CI

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by SodaqMoja** [comment]
@jwillemsen I'm not going to merge it in this state. But I want to cherry-pick 53c37ca787. I leave it up to you if 1) you want to make a new PR request, 2) reuse this PR and make the necessary changes, 3) let me do it.

The source branch of this PR contains a change in `.travis.yml` which was modified in the master branch, our master branch.

Also your source branch contains two commits that should have been squashed.

**Comment by jwillemsen** [comment]
Is the change on your master on github? If so, I can update this PR, if not, feel free to update this PR

**Comment by jwillemsen** [comment]
Will make tomorrow a new PR

**Comment by jwillemsen** [comment]
Replaced by #25

**Pull request closed without merging**
