### PR TITLE
Enable the lorawan module.

### PR DESCRIPTION
**Pull request by PanMan**
Thanks to @Jan at TTN slack, this was needed for us to get the module to transmit

### CODE REVIEW

**Comment by SodaqMoja** [comment]
Hi

Your change, which board is this for?

**Comment by hansmbakker** [comment]
@SodaqMoja from http://support.sodaq.com/lorabee/:

```
// MBili / Tatu
//#define beePin 20
// Autonomo 
#define beePin BEE_VCC

(...)

digitalWrite(beePin, HIGH);
```

I agree that this is really a pitfall, it is easy to look over...

**Comment by hansmbakker** [comment]
@SodaqMoja can you please revert that merge, since the pin that needs to be HIGH depends on the Sodaq model?

Simply hardcoding it to "20" is not a good example I think, I'd recommend following the example I quoted from sodaq.com

**Comment by SodaqMoja** [comment]
Yes, you're right.
I've changed it, but I wasn't able to test it. Can you try it out?

**Comment by hansmbakker** [comment]
I don't have the Mbili but on the Autonomo+Lorabee combination the example works well (with the proper #define)

**Pull request merged**
